---
title: "Homework5.rmd"
author: "Andre LaFleur"
date: "November 3, 2016"
output: html_document
---

# Problem 1

Let $S$ be the event that someone smokes. Let $H$ be the event that someone has a heart attack.
Below is the joint probabilities given these two events:

|   | S | S' |
|:-:|:-:|:--:|
| H | 0.03  |   0.03 |
| H'|  0.44 |   0.5 |

## Part A

The proportion of people who smoke, or also simply known as $P(S)$, is discovered by adding up the columns
of the table. Thus $P(S) = 0.03 + 0.44 = 0.47$, or 47% of the population.

## Part B

The proportion of people who have a heart attack, or $P(H)$, is again discovered by adding up the rows of the table
above. Thus $P(H) = 0.03 + 0.03 = 0.06$, or 6% of the population.

## Part C

This question asks whether $P(H|S) > P(H|S^C)$. This is relatively straightforward to solve, shown below:

$$\begin{align}
P(H|S) &> P(H|S^C) & ? \\
\frac{P(H, S)}{P(S)} &> \frac{P(H, S^C)}{P(S^C)} \\
\frac{0.03}{0.47} &> \frac{0.03}{0.53} \\
0.63829 &> 0.56603 \\
\end{align}
$$

Thus it is more likely to have a heart attack, given you are a smoker.

## Part D

This question asks what $P(S|H)$ is. Using Bayes' rule, this is can be solved:

$$\begin{align}
P(S|H) &= \frac{P(H|S)P(S)}{P(H)} \\
&= \frac{\frac{0.03}{0.47} * 0.47}{0.06} \\
&= \frac{0.03}{0.06} \\
&= \frac{1}{2} \\
\end{align}
$$

## Part E

For smoking to be independent of having a heart attack, $P(H|S) = P(H)$ and $P(S|H) = P(S)$.
Since $P(H|S) = 0.64829$ and $P(H) = 0.03$, $P(H|S) \neq P(H)$ and so the two variables are
dependent.

## Part F

The covariance of $H$ and $S$ is solved below:

$$\begin{align}
Cov(S, H) &= E[SH] - E[S]E[H] \\
&= (0 * 0 * 0.5 + 0 * 1 * 0.44 + 1 * 0 * 0.03 + 1 * 1 * 0.03) - 0.47 * 0.06 \\
&= 0.0018\\
\end{align}
$$

## Part G

The correlation of S and H, or $\rho(S, H)$, is simply the covariance divided by square root of
the product of the variances of S and H. Since S and H are Bernoulli distributions, their variances
are simply $\theta(1-\theta)$, where $\theta$ is the probability of their occurance. Thus

$$\begin{align}
\rho(S, H) &= \frac{0.0018}{\sqrt{0.47 * 0.53 * 0.06 * 0.94}}\\
&\approx 0.0151860941947\\
\end{align}
$$

# Problem 2

```{r}
# We will sample from a simple array of 00, 01, 10, and 11, where the first value is whether or
# not a heart attack occured, and the second is whether or not the person is a smoker.
trials = 10000
values = sample(c(00, 01, 10, 11), size = trials, prob = c(0.5, 0.44, 0.03, 0.03), replace = TRUE)
smokerValues = c()
heartAttackValues = c()

# We will separate everything out
for(i in values){
  isSmoker = (i == 11 || i == 01)
  hadHeartAttack = (i >= 10)
  
  if(isSmoker)
    smokerValues = c(smokerValues, 1)
  else
    smokerValues = c(smokerValues, 0)
  
  if(hadHeartAttack)
    heartAttackValues = c(heartAttackValues, 1)
  else
    heartAttackValues = c(heartAttackValues, 0)
}

# What is P(1|1)?
cat(paste("P(1|1)\t", sum(values == 11) / sum(heartAttackValues == 1), "\n"))

# What is Cov(H, S)?
cat(paste("Cov(H, S)\t", cov(heartAttackValues, smokerValues)))

# What is Cor(H, S)?
cat(paste("Cor(H, S)\t", cor(heartAttackValues, smokerValues)))
```

# Problem 3

## Part A

We can find $k$ given $f(x, y)$, and our understanding that the double integral of $f(x, y)$ must be $1$:

$$\begin{align}
1 &= \int_{0}^{\frac{\pi}{2}}\int_{0}^{\frac{\pi}{2}}ksin(x + y) dx dy\\
&= k\int_{0}^{\frac{\pi}{2}}\int_{0}^{\frac{\pi}{2}}sin(x + y) dx dy\\
&= k\int_{0}^{\frac{\pi}{2}}-cos(x + y) \big|_{0}^{\frac{\pi}{2}}dy\\
&= k\int_{0}^{\frac{\pi}{2}}-cos(\frac{\pi}{2} + y) + cos(y) dy\\
&= k(-sin(\frac{\pi}{2} + y) + sin(y) \big|_{0}^{\frac{\pi}{2}}) dy\\
&= k(1 + 1)\\
&= 2k\\
k &= \frac{1}{2}\\
\end{align}
$$

## Part B

$P(X \geq \frac{\pi}{4}, Y \leq \frac{\pi}{4})$ is solved using $f(X, y)$ and integration:

$$\begin{align}
= \frac{1}{2}\int_{0}^{\frac{\pi}{4}}\int_{\frac{\pi}{4}}^{\frac{\pi}{2}}sin(x + y) dx dy\\
= \frac{1}{2}\int_{0}^{\frac{\pi}{4}}-cos(x + y) dy \big|_{0}^{\frac{\pi}{4}}\\
= \frac{1}{2}\int_{0}^{\frac{\pi}{4}}-cos(x + y) dy \big|_{\frac{\pi}{4}}^{\frac{\pi}{2}}\\
= \frac{1}{2}\int_{0}^{\frac{\pi}{2}}-cos(\frac{\pi}{4} + y) + cos(\frac{\pi}{2} + y) dy\\
= \frac{1}{2}(-sin(\frac{\pi}{4} + y) + sin(\frac{\pi}{2} + y) \big|_{0}^{\frac{\pi}{2}})\\
= 1 - \frac{1}{\sqrt{2}}
\end{align}
$$

## Part C

The marginal probability function, $f(x)$, can be solved simply by integrating with respect to y:

$$\begin{align}
f(x) &= \frac{1}{2}\int_{0}^{\frac{\pi}{2}}sin(x + y) dy\\
&= \frac{1}{2}(-cos(x + y)\big|_{0}^{\frac{\pi}{2}})\\
&= \frac{1}{2}(-cos(x + \frac{\pi}{2}) + cos(x))\\
\end{align}
$$

## Part D

The marginal probability function, $f(y)$, can be solved simply by integrating with respect to x:

$$\begin{align}
f(x) &= \frac{1}{2}\int_{0}^{\frac{\pi}{2}}sin(x + y) dx\\
&= \frac{1}{2}(-cos(x + y)\big|_{0}^{\frac{\pi}{2}})\\
&= \frac{1}{2}(-cos(y + \frac{\pi}{2}) + cos(y))\\
\end{align}
$$

## Part E

$P(X \leq \frac{\pi}{4}, Y = \frac{\pi}{4}) = 0$, since an interval for Y is needed, not a single value.

## Part F

Assume that $X$ and $Y$ are independent. If they are independent, then $Cov(X, Y) = 0$. This is false, as
shown in part G. Therefore, $X$ and $Y$ are not independent variables.

## Part G

Below is the calculation for $Cov(X, Y)$. For brevity and my own sanity, I've ommitted a few steps, but
have shown the most important ones that actually solve the problem. I figure that you're more interested
in me showing that I know how to do the problem than just doing a tedious integration. I will
mark where I skipped a step or two and explain some more complex part of my solution:

$$\begin{align}
Cov(X, Y) &= \frac{1}{2}\int_{0}^{\frac{\pi}{2}}\int_{0}^{\frac{\pi}{2}}xysin(x + y) dx dy\\
&= \frac{1}{2}\int_{0}^{\frac{\pi}{2}}(-cos(x + y)\big|_{0}^{\frac{\pi}{2}} dy) & \text{Integration by parts}\\
&= \frac{1}{2}\int_{0}^{\frac{\pi}{2}}(-cos(y + \frac{\pi}{2}) + cos(y) dy)\\
\end{align}
$$

## Part H

# Problem 4

Don't know. Too tired to figure it out.










