---
title: "Homework 1"
author: "Andre LaFleur"
date: "August 29, 2016"
output: html_document
---

# Problem 1

If $A$ and $B$ are disjoint sets, then $A-B = A$, as there is no interesection between $A$ and $B$.
Thus $P(A-B) = P(A)$, as $P(A-B) = P(A \cap B^c) = P(A)$ for disjoint events.

# Problem 2

  a. Someone is not rich: $R^c$
  b. Someone is rich and not famous: $R \cap F^c$
  c. Someone is rich or famous: $R \cup F$
  d. Someone who is not rich or famous: $(R \cup F)^c$

# Problem 3

Given that $P(R) = 0.15$, $P(F) = 0.08$, and $P(R \cap F) = 0.06$, the solution to (a) is quite straightforward:

$$\begin{align}
P(R^c) &= 1 - P(R) &\text{Compliment Rule}\\
&= 1 - 0.15 \\
&= 0.85
\end{align}
$$

The solution to (b) is a bit more intense:

$$\begin{align}
P(R \cap F^c) &= P(R - F) &\text{Definition of set difference}\\
&= P(R) - P(R \cap F) &\text{Difference Rule}\\
&= 0.15 - 0.06 \\
&= 0.09
\end{align}
$$

The solution to (c):

$$\begin{align}
P(R \cup F) &= P(R) + P(F) - P(R \cap F) &\text{Inclusion-Exclusion Rule}\\
&= 0.15 + 0.08 - 0.06 \\
&= 0.17
\end{align}
$$

The solution to (d):

$$\begin{align}
P((R \cup F)^c) &= 1 - P(R \cup F) &\text{Compliment rule}\\
&= 1 - (P(R) + P(F) - P(R \cap F)) &\text{Inclusion-Exclusion Rule}\\
&= 1 - (0.15 + 0.08 - 0.06) \\
&= 1 - 0.17 \\
&= 0.83
\end{align}
$$

# Problem 4

Let $\Omega = \{HHH, THH, HTH, HHT, TTH, THT, HTT, TTT\}$, which represents all the possibilities of three tosses of a coin. Now let there be some collection of sets such that $some set \subseteq \Omega$, where $some set$ corresponds to some set following a rule written out in English, as provided below:

$$\begin{align}
\text{Tails is thrown exactly twice} & A = \{TTH, THT, HTT\} \\
\text{Tails is thrown at least two times} & B = \{TTT, TTH, THT, HTT\} \\
\text{Tails did not appear before heads appeared} & C = \{HHT, HTT, HTH, HHH, TTT\} \\
\text{The first throw resulted in tails} & D = \{THH, THT, TTH, TTT\} \\
\end{align}
$$

The following is a list of events using the sets above and their results:

$$\begin{align}
A^c &= \Omega - A \\ 
&= \{HHH, THH, HTH, HHT, TTT\} \\
\end{align}
$$

$$\begin{align}
A \cup (C \cap D) &= A \cup \{TTT\} \\ 
&= \{TTH, THT, HTT, TTT\} \\
\end{align}
$$

$$\begin{align}
A \cap D^c &= A \cap (\Omega - D) \\
&= A \cap \{HHH, HTH, HHT, HTT\} \\
&= \{HTT\} \\
\end{align}
$$

# Problem 5

```{r}
# Definition of the sets from problem 4
omega = c("HHH", "THH", "HTH", "HHT", "TTH", "THT", "HTT", "TTT")
A = c("TTH", "THT", "HTT")
C = c("HHT", "HTT", "HTH", "HHH", "TTT")
D = c("THH", "THT", "TTH", "TTT")

# Define the results of the set ops also from problem 4
vec1 = setdiff(omega, A) # setdiff(omega, A) = A^c
vec2 = union(A, intersect(C, D))
vec3 = intersect(A, setdiff(omega, D)) # setdiff(omega, D) = D^c

trials = 100000 # Number of trials
sampleSet = sample(omega, trials, TRUE) # The sample set

# Now we will actually calculate the probabilities
res1 = paste("Probability of A^c: ", length(sampleSet[sampleSet %in% vec1]) / trials, "; expected ", 5 / 8)
res2 = paste("Probability of A ∪ (C ∩ D): ", length(sampleSet[sampleSet %in% vec2]) / trials, "; expected ", 4 / 8)
res3 = paste("Probability of A ∩ D^c: ", length(sampleSet[sampleSet %in% vec3]) / trials, "; expected ", 1 / 8)

# Print the result
cat(paste("\n", res1, "\n", res2, "\n", res3))
```