---
title: "Homework 4"
author: "Andre LaFleur"
date: "October 18, 2016"
output: html_document
---

# Problem 1

## Part A

For $f(x)$ to be a valid probability density function, $\int_{-\infty}^{\infty} f(x) dx = 1$. Since the integral for
all values outside of the boundary $0 \leq x \leq c$ is simply zero, we can solve for c using the following integral:

$$\begin{align}
\int_{0}^{c} 4x + 1 dx &= 1 \\
2x^2 + x \big|_{0}^{c} &= 1 \\
2c^2 + c &= 1 \\
2c^2 + c - 1 &= 0 \\
c = \frac{1}{2} \text{or} -1 &\text{By the quadratic equation} \\
\end{align}
$$

Since the boundary $0 \leq x \leq -1$ doesn't make much sense, $c = \frac{1}{2}$

## Part B

The expected value of X, $E[X]$, is given by the following equation: $$E[X] = \int_0^{\frac{1}{2}} x f(x) dx$$

The value then of $E[X]$ is the following:

$$\begin{align}
\int_{0}^{1/2} 4x^2 + x dx &= \frac{4x^3}{3} + \frac{x^2}{2} \big|_0^{\frac{1}{2}}\\
&= \frac{\frac{1}{2}}{3} + \frac{1}{8}\\
&= \frac{7}{24}
\end{align}
$$

## Part C

The variance of X, or $Var(X)$, can be solved given the formula $Var(X) = E[X^2] - E[X]^2$. Thus we can solve
for the value of the variance:

$$\begin{align}
E[X^2] - E[X]^2\\
\int_0^{\frac{1}{2}} x^2 f(x) dx - (\frac{7}{24})^2\\
\int_0^{\frac{1}{2}} 4x^3 + x^2 dx - (\frac{7}{24})^2\\
x^4 + \frac{x^3}{3} \big|_0^{\frac{1}{2}} - (\frac{7}{24})^2\\
\frac{1}{16} + \frac{1}{24} - (\frac{7}{24})^2\\
\approx 0.0190972
\end{align}
$$

## Part D

Let $g(x) = 2X + 3 = 2f(x) + 3 = 8x + 5$. Since $E[2X + 3] = E[g(x)]$, we can solve for this expected value
as follows:

$$\begin{align}
\int_{0}^{\frac{1}{2}}g(x)f(x)dx\\
\int_{0}^{\frac{1}{2}}(8x+5)(4x+1)dx\\
\int_{0}^{\frac{1}{2}}32x^2+28x+5dx\\
\frac{32x^3}{3}+14x^2+5x \big|_0^{\frac{1}{2}}\\
\frac{4}{3} + \frac{7}{2} + \frac{5}{2}\\
\frac{22}{3}
\end{align}
$$

## Part E

# Problem 2

Let $X ~ Geom(\Theta)$, where $\Theta = 0.5$, the probability of getting a heads after flipping a fair coin. This implies then
that $E[X] = \frac{1}{\Theta} = 2$. Since we are searching for the expected value of getting three heads, we are actually
looking for $E[3X] = 3E[X] = 2 * 3 = 6$. Therefore, if we flip a fair coin until we get three heads, the expected value would
be $6$.

# Problem 3



# Problem 4
# Problem 5

Let $X: [1, 6] \rightarrow [0, 2]$, Wherein the random variable $X$ maps the set $\{1, 2\}$ onto $0$, $\{3, 4, 5\}$ onto $1$, and $\{6\}$ onto $2$.

## Part A

The expected value of X, $E[X]$, is given below:

$$\begin{align}
E[X] &= \sum_{i=0}^{2}a_iP(X = a_i) & \text{Definition of E[X] for a discrete random variable}\\
&= 0(\frac{1}{3}) + 1(\frac{1}{2}) + 2(\frac{1}{6})\\
&= \frac{5}{6}
\end{align}
$$

## Part B

The variance of $X$, $Var(X)$, is found as follows:

$$\begin{align}
E[(X-E[X])^2] &= \sum_{i=0}^{2}P(X = i)(i - \frac{5}{6})^2 & \text{Definition of Var(X) for a discrete random variable}\\
&= \frac{1}{3}(- \frac{5}{6})^2 + \frac{1}{2}(\frac{1}{6})^2 + \frac{1}{6}(\frac{7}{6})^2\\
&= \frac{1}{3}\frac{25}{36} + \frac{1}{2}\frac{1}{36} + \frac{1}{6}\frac{49}{36}\\
&= \frac{25}{108} + \frac{1}{72} + \frac{49}{216}\\
&\approx0.4722222
\end{align}
$$

## Part C

This is not a game you would like to play if you like jelly beans. Since the expected number of jelly beans that you
would get per round ends up being $\frac{5}{6}$, and it costs a jelly bean each time you play, you would expect
to lose $1 - \frac{5}{6} = \frac{1}{6}$ jellybeans per round. 

# Problem 6
```{r}
trials = 40000
jellybeans = c()

for(i in 1:trials){
  dieRoll = sample(c(1, 2, 3, 4, 5, 6), 1, replace = TRUE)
  
  if(dieRoll <= 2){
    jellybeans[i] = 0
  } else if(dieRoll <= 5){
    jellybeans[i] = 1
  } else {
    jellybeans[i] = 2
  }
}

cat(paste("Expected value of jellybeans: ", mean(jellybeans)))
```

# Extra Credit













